name: "Setup JDK"
description: "setup JDK and gradle & konan caching"

runs:
  using: "composite"
  steps:
    - name: Validate Gradle Wrapper
      uses: gradle/actions/wrapper-validation@v4

    - name: Copy CI gradle.properties
      shell: bash
      run: |
        mkdir -p ~/.gradle
        cp .github/ci-gradle.properties ~/.gradle/gradle.properties

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: wrapper

    - name: Cache Gradle dependencies & build outputs
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          .gradle
        key: |
          ${{ runner.os }}-gradle-\
          ${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties','gradle/libs.versions.toml') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Set Konan Cache Key
      id: konan-cache-key
      shell: bash
      run: echo "KOTLIN_VERSION=$(grep -oE 'kotlin\s*=\s*"[0-9.]*"' gradle/libs.versions.toml | grep -oE '[0-9.]+')" >> $GITHUB_OUTPUT

    - name: Cache Konan
      uses: actions/cache@v4
      with:
        path: |
          ~/.konan
        key: v1-konan-${{ runner.os }}-${{ hashFiles('.xcode-version') }}-${{ steps.konan-cache-key.outputs.KOTLIN_VERSION }}
