# https://github.com/DroidKaigi/conference-app-2024/blob/main/.github/workflows/detekt.yml
name: Static Analysis (Detekt)

on:
  push:
    branches:
      - 2025/compose-multiplatform
  pull_request:

jobs:
  detekt:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Run detekt
        run: ./gradlew detekt --stacktrace

      - name: Save PR event
        if: failure()
        run: |
          mkdir -p ./pr
          echo '${{ toJson(github.event) }}' > ./pr/event.json

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: pr
          path: pr/