name: Compose Desktop(JVM) CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ 2025/compose-multiplatform ]
    paths-ignore:
      - 'iosApp/**'
      - 'kotlin-js-store/**'
  push:
    branches: [ 2025/compose-multiplatform ]
    paths-ignore:
      - 'iosApp/**'
      - 'kotlin-js-store/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Build Desktop Jar
        run: ./gradlew :composeApp:desktopJar --stacktrace

      - name: Upload artifact for PR
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-jar
          path: composeApp/build/libs/*.jar
          retention-days: 1

      - name: Upload artifact for 2025/compose-multiplatform
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: desktop-jar
          path: composeApp/build/libs/*.jar
          retention-days: 3
