name: Compose Desktop(JVM) CI

on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ 2025/compose-multiplatform ]
    paths-ignore:
      - 'iosApp/**'
      - 'kotlin-js-store/**'
  push:
    branches: [ 2025/compose-multiplatform ]
    paths-ignore:
      - 'iosApp/**'
      - 'kotlin-js-store/**'

permissions:
  contents: read

jobs:
  windows:
    name: 🪟 Windows Build
    runs-on: windows-latest
    outputs:
      artifact_url: ${{ steps.upload.outputs.artifact-upload-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Package MSI
        run: ./gradlew :composeApp:packageMsi --stacktrace
      - name: Upload Windows Installer
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: desktop-msi
          path: composeApp/build/compose/binaries/main/msi/*.msi

  macos:
    name: 🍎 macOS Build
    runs-on: macos-latest
    outputs:
      artifact_url: ${{ steps.upload.outputs.artifact-upload-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Package DMG
        run: ./gradlew :composeApp:packageDmg --stacktrace
      - name: Upload macOS Installer
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: desktop-dmg
          path: composeApp/build/compose/binaries/main/dmg/*.dmg

  linux:
    name: 🐧 Linux Build
    runs-on: ubuntu-latest
    outputs:
      artifact_url: ${{ steps.upload.outputs.artifact-upload-url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: ./.github/actions/setup-java
      - name: Install Debian packaging tools
        run: |
          sudo apt-get update
          sudo apt-get install -y fakeroot dpkg-dev
      - name: Package DEB
        run: ./gradlew :composeApp:packageDeb --stacktrace
      - name: Upload Linux Installer
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: desktop-deb
          path: composeApp/build/compose/binaries/main/deb/*.deb
  comment:
    name: 💬 Comment Build Status
    needs: [ windows, macos, linux ]
    runs-on: ubuntu-latest
    if: ${{ always() && github.event_name == 'pull_request' }}
    steps:
      - name: Post summary comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          body: |
            🚀 **빌드 결과 요약**
            - 🪟 Windows: ${{ needs.windows.result == 'success' && needs.windows.outputs.artifact_url || '❌ 빌드가 실패하였습니다' }}
            - 🍎 macOS: ${{ needs.macos.result  == 'success' && needs.macos.outputs.artifact_url  || '❌ 빌드가 실패하였습니다' }}
            - 🐧 Linux:  ${{ needs.linux.result == 'success' && needs.linux.outputs.artifact_url || '❌ 빌드가 실패하였습니다' }}
