name: Compose Wasm(Web) Build

on:
  push:
    branches:
      - 2025/compose-multiplatform
  pull_request:
    paths-ignore:
      - 'iosApp/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: { }

jobs:
  build:
    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: kotlinUpgradeYarnLock
        run: ./gradlew kotlinUpgradeYarnLock

      - run: ./gradlew :composeApp:buildWebApp --stacktrace
