# From KotlinConf App
# https://github.com/JetBrains/kotlinconf-app/blob/main/.github/workflows/web-deploy.yml
name: Publish Wasm App on GitHub Pages
on:
  push:
    branches:
      - develop-2025
  workflow_dispatch:
  pull_request:
    branches:
      - develop-2025

jobs:
  # Build job
  build:
    name: Build Kotlin/Wasm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-java

      - name: Run Gradle Tasks
        run: ./gradlew :composeApp:buildWebApp

      - name: Fix permissions
        run: |
          chmod -v -R +rX "composeApp/build/webApp/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: composeApp/build/webApp/

  deploy:
    # Add a dependency to the build job
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Debug Permissions
        run: env | grep ACTIONS_ID_TOKEN_REQUEST_URL || echo "ACTIONS_ID_TOKEN_REQUEST_URL not set"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
